const express = require("express")
const router = express.Router()

const requestsController = require("../controllers/rda_requests")
const verifyToken = require('../middleware/token')
const rbacMiddleware = require('../middleware/rbacMiddleware')

router.get("/",verifyToken, rbacMiddleware.checkPermission("read_all_requests") ,requestsController.getRequests)
router.get("/search",verifyToken, rbacMiddleware.checkPermission("search_rda") ,requestsController.searchRDA)
router.get("/:id/approval-history", verifyToken, rbacMiddleware.checkPermission("read_approval_timeline"), requestsController.getApprovalHistory)
router.get("/awaiting-approval",verifyToken, rbacMiddleware.checkPermission("read_pending_rda"), requestsController.getPendingRda)
router.get("/mine", verifyToken, rbacMiddleware.checkPermission("read_personal_requests"), requestsController.getUsersRequests)
router.get("/approved", verifyToken, rbacMiddleware.checkPermission("read_approved_rdas"), requestsController.getApprovedRDA)
router.get("/procurement-pending", verifyToken, rbacMiddleware.checkPermission("read_pending_list"), requestsController.pendingList)
router.get("/:id/next-approver", verifyToken, rbacMiddleware.checkPermission("read_next_approver"), requestsController.nextApprover)
router.get("/:id/all-approvers", verifyToken, rbacMiddleware.checkPermission("read_all_approvers"), requestsController.allApprovers)
router.get("/procurement-pending", verifyToken, rbacMiddleware.checkPermission("read_pending_list"), requestsController.pendingList)
router.post("/:id/close", verifyToken,rbacMiddleware.checkPermission("close_request") ,requestsController.closeRequest)
router.get("/area", verifyToken, rbacMiddleware.checkPermission("read_area_RDA"), requestsController.getUsersDepartmentsRDA)
router.get("/stats/summary", verifyToken,rbacMiddleware.checkPermission("read_rda_stats"), requestsController.getRdaStats)
router.get("/:id/attachments", verifyToken,rbacMiddleware.checkPermission("read_rda_attachments"), requestsController.getRdaAttachments)
router.get("/:id", verifyToken,rbacMiddleware.checkPermission("read_rda_byId"), requestsController.getRequestById)
router.post("/submit", verifyToken, rbacMiddleware.checkPermission("submit_request"), requestsController.submitRDA)
router.post("/:id/submit", verifyToken, rbacMiddleware.checkPermission("submit_request"), requestsController.submitRDAID)
router.post("/draft", verifyToken, rbacMiddleware.checkPermission("draft_request"), requestsController.draftRda)
router.post("/", verifyToken, rbacMiddleware.checkPermission("create_request"), requestsController.createRequest)
router.post("/:id/attachments", verifyToken, rbacMiddleware.checkPermission("upload_attachments"),requestsController.uploadAttachment)
router.post("/:id/invoice", verifyToken, rbacMiddleware.checkPermission("upload_invoice"),requestsController.uploadInvoice)
router.post("/:id/approve", verifyToken,rbacMiddleware.checkPermission("approve_rda"),requestsController.approveRequest)
router.put("/:id", verifyToken, rbacMiddleware.checkPermission("edit_request"), requestsController.updateRequest)
router.delete("/:id", verifyToken, rbacMiddleware.checkPermission("delete_request"),requestsController.deleteRequest)
router.delete("/", verifyToken, rbacMiddleware.checkPermission("delete_latest_request"),requestsController.deleteLatestRequest)
router.post("/:id/reject", verifyToken, rbacMiddleware.checkPermission("reject_request"),requestsController.rejectRequest)
router.post("/:id/mark-ordered", verifyToken, rbacMiddleware.checkPermission("mark_ordered"),requestsController.markOrdered)

module.exports = router